"""agregar localidad a cliente para mapa de ventas

Revision ID: 03d53572032b
Revises: 04f3140a05c6
Create Date: 2026-09-06 10:39:03.780682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d53572032b'
down_revision: Union[str, None] = '04f3140a05c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('localidad', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'localidad')
    # ### end Alembic commands ###
