"""agregar ciudad, estado/ultima_sesion usuario, campos reporte_generado

Revision ID: 04f3140a05c6
Revises: 2bc824c859e3
Create Date: 2026-09-06 10:35:14.601227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f3140a05c6'
down_revision: Union[str, None] = '2bc824c859e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('ciudad', sa.String(length=100), nullable=True))
    op.add_column('reporte_generado', sa.Column('nombre', sa.String(length=200), nullable=True))
    op.add_column('reporte_generado', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('reporte_generado', sa.Column('archivo_path', sa.String(length=500), nullable=True))
    op.add_column('usuario', sa.Column('estado', sa.String(length=20), nullable=True))
    op.add_column('usuario', sa.Column('ultima_sesion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'ultima_sesion')
    op.drop_column('usuario', 'estado')
    op.drop_column('reporte_generado', 'archivo_path')
    op.drop_column('reporte_generado', 'tipo')
    op.drop_column('reporte_generado', 'nombre')
    op.drop_column('cliente', 'ciudad')
    # ### end Alembic commands ###
