"""crear tablas iniciales

Revision ID: 2bc824c859e3
Revises: 
Create Date: 2026-08-29 18:01:27.658694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc824c859e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('autorizacion_datos', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('modelo_prediccion',
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('fecha_entrenamiento', sa.DateTime(), nullable=True),
    sa.Column('precision_modelo', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_modelo')
    )
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('analisis_comportamiento',
    sa.Column('id_analisis', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('frecuencia_compra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('promedio_gasto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prediccion_recompra', sa.DateTime(), nullable=True),
    sa.Column('fecha_analisis', sa.DateTime(), nullable=True),
    sa.Column('nivel_satisfaccion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_analisis')
    )
    op.create_table('importacion_interacciones',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_importacion', sa.DateTime(), nullable=True),
    sa.Column('tipo_interaccion', sa.String(length=50), nullable=True),
    sa.Column('fuente_archivo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado_pedido', sa.String(length=50), nullable=True),
    sa.Column('canal', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('prediccion_cliente',
    sa.Column('id_prediccion', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('fecha_prediccion', sa.DateTime(), nullable=True),
    sa.Column('probabilidad_recompra', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('riesgo_abandono', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelo_prediccion.id_modelo'], ),
    sa.PrimaryKeyConstraint('id_prediccion')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('detalle_pedido',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('log_actividad',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('reporte_generado',
    sa.Column('id_reporte', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('formato', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reporte')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte_generado')
    op.drop_table('log_actividad')
    op.drop_table('detalle_pedido')
    op.drop_table('usuario')
    op.drop_table('prediccion_cliente')
    op.drop_table('pedido')
    op.drop_table('importacion_interacciones')
    op.drop_table('analisis_comportamiento')
    op.drop_table('rol')
    op.drop_table('producto')
    op.drop_table('modelo_prediccion')
    op.drop_table('cliente')
    # ### end Alembic commands ###
