"""agregar origen_hash a detalle_pedido para deteccion de duplicados

Revision ID: a01811ef8767
Revises: 03d53572032b
Create Date: 2026-10-01 22:19:51.417672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01811ef8767'
down_revision: Union[str, None] = '03d53572032b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_pedido', sa.Column('origen_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_detalle_pedido_origen_hash'), 'detalle_pedido', ['origen_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_pedido_origen_hash'), table_name='detalle_pedido')
    op.drop_column('detalle_pedido', 'origen_hash')
    # ### end Alembic commands ###
